### ISSUE TITLE
I have an issue.

### ISSUE THREAD

**Issue by scheijan** [OleaBlossom/nameGame#1]
With your naming conventions in your code - either '_' or camel notation please ;)

**Comment by OleaBlossom** [comment]
Nice catch! I'll take care of that ASAP.

**Comment by OleaBlossom** [comment]
@scheijan not only did I homogenise the code to be more pythonic (consistently using an underscore instead of camel case), I also took the opportunity to make the variables a little more suggestive of their job and split long lines into more variables. I hope you find the latest commit satisfactory!
